czech_stop_words = [
    "a", "aby", "aj", "ale", "anebo", "ani", "aniž", "ano", "asi", "až",
    "bez", "beze", "bude", "budem", "budeme", "budes", "budete", "budeš",
    "budou", "budu", "by", "byl", "byla", "byli", "bylo", "byly", "bys",
    "byt", "být", "bývat", "chce", "chceme", "chceš", "chcete", "chci",
    "chtějí", "chtít", "chuti", "co", "coz", "což", "cz", "čau",
    "či", "článek", "článku", "články", "čtrnáct", "čtyři", "daleko",
    "dalsi", "dalsim", "další", "den", "deset", "devatenáct", "devět",
    "dnes", "do", "dobrý", "docela", "dva", "dvacet", "dvanáct", "dvě",
    "dál", "dále", "děkovat", "děkujeme", "děkuji", "děkuju", "ho",
    "hodně", "i", "já", "jak", "jako", "je", "jeden", "jedenáct", "jedna",
    "jedno", "jednou", "jedou", "jeho", "jej", "jeji", "jejich", "její",
    "jelikož", "jemu", "jen", "jenom", "jenž", "ještě", "jež", "ji",
    "jich", "jimi", "jinak", "jiné", "již", "jiz", "jsem", "jses", "jsi",
    "jsme", "jsou", "jste", "jšte", "k", "kam", "kde", "kdo", "kdy",
    "kdyz", "když", "ke", "kolik", "kromě", "ktera", "ktere", "kteri",
    "kterou", "ktery", "který", "kteři", "kteří", "ku", "kvuli", "ma",
    "mají", "má", "málo", "mám", "máme", "máš", "máte", "mé", "mě",
    "mezi", "mi", "mít", "mne", "mnou", "mně", "moc", "mohl", "mohou",
    "moje", "moji", "možná", "můj", "musí", "může", "my", "na", "nad",
    "nade", "nám", "námi", "naproti", "napiste", "napište", "nás", "náš",
    "naše", "naši", "ne", "ně", "nebo", "nebyl", "nebyla", "nebyli",
    "nebyly", "nechť", "něco", "nedělá", "nedělají", "nedělám", "neděláme",
    "neděláš", "neděláte", "nějak", "někde", "někdo", "několik", "němci",
    "němu", "není", "nestačí", "nevadí", "než", "nic", "nich", "ním",
    "nimi", "nula", "ná", "ní", "o", "od", "ode", "on", "ona", "oni",
    "ono", "ony", "osm", "osmnáct", "pak", "patnáct", "pět", "po", "pod",
    "podle", "pokud", "pouze", "pozdě", "před", "přede", "přes", "přese",
    "pro", "proč", "prosím", "prostě", "proti", "proto", "protože",
    "prvni", "první", "pta", "re", "rovně", "s", "se", "sedm", "sedmnáct",
    "si", "sice", "skoro", "smějí", "smí", "snad", "spolu", "sta", "sté",
    "sto", "strana", "své", "svých", "svým", "svými", "ta", "tady", "tak",
    "takhle", "taky", "také", "takže", "tam", "tamhle", "tamhleto",
    "tamto", "tato", "tedy", "tě", "těma", "te", "tebe", "tebou",
    "ten", "ti", "tisíc", "tisíce", "to", "tobě", "tohle", "toto", "třeba",
    "tři", "třináct", "trošku", "tvá", "tvé", "tvoje", "tvůj", "ty",
    "u", "určitě", "už", "v", "vám", "vámi", "vás", "váš", "vaše", "vaši",
    "ve", "večer", "vedle", "vice", "vlastně", "však", "všechno", "všichni",
    "vůbec", "vy", "vždy", "za", "zač", "zatímco", "zda", "zde", "ze",
    "zpět", "zprávy", "že"
]